apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: us.icr.io/sn-labs-jffgrcjg/accounts:1
        resources: {}
        env:
          - name: DATABASE_HOST
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: deploy
          runAfter:
          - build
          workspaces:
          - name: manifest-dir
          workspace: pipeline-workspace
          taskRef:
          name: openshift-client
          kind: ClusterTask
          params:
          - name: SCRIPT
          value: |
          echo "Updating manifest..."
          # Using sed to swap the placeholder for the fresh image
          sed -i "s|IMAGE_NAME_HERE|$(params.build-image)|g" deploy/deployment.yaml
          cat deploy/deployment.yaml
          echo "Deploying to OpenShift..."
          oc apply -f deploy/
          oc get pods -l app=accounts
                